name: JavaScript

on:
  push:
    branches:
      - main

jobs:
  build:
    name: JS / Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@master

      - uses: flarum/action-build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
